### ISSUE TITLE
Replace QT State Machine as underlying state machine framework

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/packml#17]
The QT state machine framework is currently used as the basis for the packml state machine.  QT is licensed as LGPL, which could be problematic for embedded devices (see [here](https://www.qt.io/licensing/)).  I believe embedded devices are different because the user cannot substitute their own version of the QT library as is required (see [here](https://www.qt.io/qt-licensing-terms/)).  

To avoid this licensing ambiguity, I suggest we start using the Boost [meta-state machine framework](http://www.boost.org/doc/libs/1_63_0/libs/msm/doc/HTML/index.html).  The Boost framework is very similar and should make a good drop in replacement.

**Comment by joshuaplusone** [comment]
@shaun-edwards After reviewing the code I would like to make the following changes:

- [ ] In packml_sm Replace qt state machine framework with boost state machine framework.
- [ ] In packml_sm Create a static logger instead of calling directly ROS loggers.
- [ ] In packml_sm Separate each of the state machine types to their own .cpp/.h files  (when I do this, any external code that relies on this library will need to update their .h references to the new ones.)

Do you agree?

**Comment by shaun-edwards** [comment]
>Replace qt state machine framework with boost state machine framework.

Just to make sure, will we keep the Qt state machine around for backwards compatibility?

>Create a static logger instead of calling directly ROS loggers.

I assume you will do this in a way that logs nicely to ROS when it's in use

> Separate each of the state machine types to their own .cpp/.h files (when I do this, any external code that relies on this library will need to update their .h references to the new ones.)

To avoid breaking other's code, can we still keep the "top level" header?  Sort of like OpenCV does it with `opencv.h`?

**Comment by shaun-edwards** [comment]
Addressed in #35
