### ISSUE TITLE
Wiki page on ros.org not showing any content

### ISSUE THREAD

**Issue by 130s** [ros-industrial-consortium/packml#45]
http://wiki.ros.org/packml

Wiki content looks ok to me. Its doc entry is [listed on rosdistro](https://github.com/ros/rosdistro/blob/ec8e307af6f43bf1a3f1df507fda07f6ceacec96/kinetic/distribution.yaml#L7550) (added in https://github.com/ros/rosdistro/pull/15737). "Documentation Status" link shows empty.

@tfoote sorry to bother you but do you have a way to see doc job log etc.?

**Comment by tfoote** [comment]
There's no packml package so that's why there's no content for the macro on that page. 

You can find the doc job here: http://build.ros.org/job/Kdoc__packml__ubuntu_xenial_amd64/ They're all publicly logged. 

And you can see it's generating content for 4 packages with similar but different names output here: https://docs.ros.org/kinetic/api/

**Comment by 130s** [comment]
Thanks for taking a look @tfoote.
I confirmed the pages for existing specific packages are already generated e.g. http://wiki.ros.org/packml_ros. Removed http://wiki.ros.org/packml page.
